# -*- coding: utf-8 -*-
{
    'name': "supermodulo18",

    'summary': "Short (1 phrase/line) summary of the module's purpose",

    'description': """
Long description of module's purpose
    """,

    'author': "My Company",
    'website': "https://www.yourcompany.com",

    # Categories can be used to filter modules in modules listing
    # Check https://github.com/odoo/odoo/blob/15.0/odoo/addons/base/data/ir_module_category_data.xml
    # for the full list
    'category': 'Uncategorized',
    'version': '0.1',

    # any module necessary for this one to work correctly
    'depends': [

        'account_payment_sale',
        'report_xlsx_helper',
        'account_due_list_payment_mode',
        'base_location_geonames_import',
        'account_payment_purchase',
        'base_bank_from_iban',
        'product',
        'uom',
        'mail',
        'sales_team',
        'account_payment_purchase_stock',
        'account_edi_ubl_cii',
        'account_usability',
        'account_lock_date_update',
        'calendar',
        'crm',
        'board',
        'hr_holidays',
        'purchase',
        'account_move_template',
        'date_range',
        'report_xlsx',
        'hr_skills',
        'date_range_account',
        'hr_attendance',
        'hr_holidays_attendance',
        'auth_totp_portal',
        'hr_expense',
        'project_stock',
        'barcodes_gs1_nomenclature',
        'project_tag_security',
        'project_tag_hierarchy',
        'website_links',
        'project_tag_multicompany',
        'sale_product_template_tags',
        'purchase_stock',
        'base_iban',
        'mass_mailing_themes',
        'website_project',
        'project_hr_expense',
        'base_vat',
        'website_crm',
        'website_mass_mailing',
        'purchase_edi_ubl_bis3',
        'project_hr_skills',
        'project_purchase',
        'project_stock_account',
        'sale_edi_ubl',
        'hr_org_chart',
        'crm_sms',
        'sale',
        'sale_project_stock',
        'sale_project_stock_account',
        'sale_purchase_project',
        'http_routing',
        'purchase_mrp',
        'sale_management',
        'base_search_custom_field_filter',
        'iap_crm',
        'onboarding',
        'iap_mail',
        'partner_autocomplete',
        'phone_validation',
        'portal',
        'project_account',
        'resource',
        'sale_crm',
        'sale_project',
        'sale_purchase',
        'mass_mailing_crm',
        'sale_stock',
        'sale_timesheet',
        'sms',
        'spreadsheet_dashboard_hr_expense',
        'spreadsheet_dashboard_stock_account',
        'stock_account',
        'stock_sms',
        'project_purchase_stock',
        'project_sms',
        'social_media',
        'hr_attendance_reason',
        'resource_mail',
        'base_import',
        'sale_purchase_stock',
        'server_action_mass_edit',
        'account_invoice_refund_link',
        'web_hierarchy',
        'account_chart_update',
        'account_invoice_report_payment_info',
        'l10n_es_edi_facturae',
        'analytic',
        'account_payment',
        'remove_odoo_enterprise',
        'certificate',
        'auth_signup',
        'base_install_request',
        'calendar_sms',
        'account_edi_proxy_client',
        'google_recaptcha',
        'contacts',
        'base_import_module',
        'account',
        'google_gmail',
        'l10n_es',
        'sale_mrp',
        'spreadsheet_dashboard_account',
        'portal_rating',
        'snailmail_account',
        'project_sale_expense',
        'mass_mailing_sale',
        'payment',
        'account_payment_partner',
        'account_payment_order',
        'base_address_extended',
        'account_tax_balance',
        'website_mail',
        'base',
        'utm',
        'web_unsplash',
        'website_payment',
        'account_asset_management',
        'account_due_list',
        'spreadsheet_dashboard_sale_timesheet',
        'sale_sms',
        'account_financial_report',
        'account_payment_mode',
        'account_move_name_sequence',
        'account_move_line_stock_info',
        'sale_service',
        'account_reconcile_model_oca',
        'account_statement_base',
        'account_reconcile_oca',
        'account_statement_import_base',
        'auto_backup',
        'snailmail',
        'spreadsheet',
        'spreadsheet_dashboard_sale',
        'base_sparse_field_list_support',
        'base_partner_sequence',
        'contract',
        'document_knowledge',
        'document_page',
        'web_no_bubble',
        'l10n_es_aeat',
        'l10n_es_account_banking_sepa_fsdd',
        'l10n_es_aeat_mod111',
        'l10n_es_account_asset',
        'l10n_es_aeat_mod303',
        'l10n_es_account_statement_import_n43',
        'l10n_es_mis_report',
        'l10n_es_toponyms',
        'l10n_es_partner',
        'mis_builder',
        'mis_builder_budget',
        'product_attribute_value_archive',
        'web_chatter_position',
        'web_responsive',
        'website',
        'barcodes',
        'rating',
        'hr_calendar',
        'mass_mailing',
        'hr',
        'stock',
        'digest',
        'crm_iap_enrich',
        'link_tracker',
        'crm_iap_mine',
        'project_mrp',
        'project_mrp_account',
        'project_mrp_sale',
        'product_margin',
        'mrp',
        'mail_bot',
        'mail_bot_hr',
        'project',
        'sale_async_emails',
        'sale_expense',
        'sale_pdf_quote_builder',
        'website_sms',
        'website_crm_sms',
        'spreadsheet_dashboard',
        'spreadsheet_account',
        'project_todo',
        'base_technical_features',
        'web_editor',
        'account_peppol',
        'account_qr_code_sepa',
        'account_banking_pain_base',
        'account_banking_sepa_direct_debit',
        'account_banking_mandate',
        'account_invoice_overdue_warn',
        'account_invoice_line_report',
        'account_payment_promissory_note',
        'account_move_line_sale_info',
        'account_statement_import_file',
        'account_payment_term_extension',
        'account_statement_import_file_reconcile_oca',
        'base_location',
        'document_url',
        'disable_odoo_online',
        'privacy_lookup',
        'mrp_account',
        'auth_totp_mail',
        'hr_hourly_cost',
        'html_editor',
        'bus',
        'iap',
        'account_edi',
        'base_setup',
        'base_sparse_field',
        'spreadsheet_dashboard_hr_timesheet',
        'hr_timesheet',
        'project_timesheet_holidays',
        'web_tour',
        'hr_timesheet_attendance',
        'auth_totp',
        'web'
],

    # always loaded
    'data': [
        # 'security/ir.model.access.csv',
        'views/views.xml',
        'views/templates.xml',
    ],
    # only loaded in demonstration mode
    'demo': [
        'demo/demo.xml',
    ],
}

